apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: node-app
spec:
  selector:
    app: nodeapp
  type: NodePort
  ports:
    - name: login
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30001
    - name: mainapp
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30000