apiVersion: v1
kind: Service
metadata:
  name: node-service
  namespace: node-app
spec:
  selector:
    app: nodeapp
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: login
      port: 3001
      targetPort: 3001
      nodePort: 3001
    - protocol: TCP
      name: mainapp
      port: 3000
      targetPort: 3000
      nodePort: 3000
